services:
  firmador:
    container_name: firmador
    build: firmadorJavaSpring
    ports:
      - "8443:8443"
    environment:
      - API_PROTOCOL=https
      - API_HOST=lucia.arlabdevelopments.com
      - API_PORT=3000
      - API_URI=jws
      - gx-terms-and-conditions=70c1d713215f95191a11d38fe2341faed27d19e083917bc8732ca4fea4976700
      - API_NumRegistration=https://gx-notary.arsys.es/v1/registrationNumberVC?
      - API_TerminosYParticipante=https://compliance.arlabdevelopments.com/v1-staging/api/credential-offers?vcid=
      - issuer_Participant=did:web:gx-notary.arsys.es:v1
      - issuer_Terminos=did:web:arlabdevelopments.com
     
      
    volumes:
      - ./keystore.p12:/app/keystore.p12:ro
  api:
    container_name: api
    build: JSFirmador
    env_file:
      - .env_api
    ports:
      - "3000:3000"



      
